### ISSUE TITLE
Panel disappears when switching back to viewer mode

### ISSUE THREAD

**Issue by catamounts** [DevExpress/dashboard-extension-dashboard-panel#3]
After switching to designer mode, clicking on the Viewer button causes the panel to disappear.   The cause appears to be a typo in "this.desingerToViewerAction =".  Changing this to "this.designerToViewerAction =" fixes the issue.  The typo exists in both dashboard-panel.js and dashboard-panel.min.js.  

Cheers

**Comment by dimarudnev** [comment]
Hi Cheers,
Thank you for reporting the issue. To get the fix, you can get the latest version of the master branch.
